data:
  main:
    driver: ${X_MOON_DATA_MAIN_DRIVER:MYSQL}
    debug: ${X_MOON_DATA_MAIN_DEBUG:true}
    use_system_log: ${X_MOON_DATA_MAIN_USE_SYSTEM_LOG:false}
    user: ${X_MOON_DATA_MAIN_USER:root}
    password: ${X_MOON_DATA_MAIN_PASSWORD:123456}
    host: ${X_MOON_DATA_MAIN_HOST:127.0.0.1}
    port: ${X_MOON_DATA_MAIN_PORT:3306}
    params: ${X_MOON_DATA_MAIN_PARAMS:charset=utf8mb4&parseTime=True&loc=Local}
    db_name: ${X_MOON_DATA_MAIN_DB_NAME:moon_palace_main}
  biz:
    driver: ${X_MOON_DATA_BIZ_DRIVER:MYSQL}
    debug: ${X_MOON_DATA_BIZ_DEBUG:true}
    use_system_log: ${X_MOON_DATA_BIZ_USE_SYSTEM_LOG:false}
    user: ${X_MOON_DATA_BIZ_USER}
    password: ${X_MOON_DATA_BIZ_PASSWORD}
    host: ${X_MOON_DATA_BIZ_HOST:127.0.0.1}
    port: ${X_MOON_DATA_BIZ_PORT:3306}
    params: ${X_MOON_DATA_BIZ_PARAMS:charset=utf8mb4&parseTime=True&loc=Local}
    db_name: ${X_MOON_DATA_BIZ_DB_NAME:moon_palace_biz}
  alarm:
    driver: ${X_MOON_DATA_ALARM_DRIVER:MYSQL}
    debug: ${X_MOON_DATA_ALARM_DEBUG:true}
    use_system_log: ${X_MOON_DATA_ALARM_USE_SYSTEM_LOG:false}
    user: ${X_MOON_DATA_ALARM_USER:root}
    password: ${X_MOON_DATA_ALARM_PASSWORD:123456}
    host: ${X_MOON_DATA_ALARM_HOST:127.0.0.1}
    port: ${X_MOON_DATA_ALARM_PORT:3306}
    params: ${X_MOON_DATA_ALARM_PARAMS:charset=utf8mb4&parseTime=True&loc=Local}
    db_name: ${X_MOON_DATA_ALARM_DB_NAME:moon_palace_alarm}

cache:
  driver: ${X_MOON_CACHE_DRIVER:MEMORY}
  network: ${X_MOON_CACHE_NETWORK:tcp}
  addr: ${X_MOON_CACHE_ADDR:127.0.0.1:6379}
  password: ${X_MOON_CACHE_PASSWORD}
  db: ${X_MOON_CACHE_DB:0}
  read_timeout: ${X_MOON_CACHE_READ_TIMEOUT:5s}
  write_timeout: ${X_MOON_CACHE_WRITE_TIMEOUT:5s}
  dial_timeout: ${X_MOON_CACHE_DIAL_TIMEOUT:5s}
  client_name: ${X_MOON_CACHE_CLIENT_NAME}
  protocol: ${X_MOON_CACHE_PROTOCOL:0}
  username: ${X_MOON_CACHE_USERNAME}
  max_retries: ${X_MOON_CACHE_MAX_RETRIES:0}
  min_retry_backoff: ${X_MOON_CACHE_MIN_RETRY_BACKOFF:0s}
  max_retry_backoff: ${X_MOON_CACHE_MAX_RETRY_BACKOFF:0s}
  context_timeout_enabled: ${X_MOON_CACHE_CONTEXT_TIMEOUT_ENABLED:false}
  pool_fifo: ${X_MOON_CACHE_POOL_FIFO:false}
  pool_size: ${X_MOON_CACHE_POOL_SIZE:0}
  pool_timeout: ${X_MOON_CACHE_POOL_TIMEOUT:0s}
  min_idle_conns: ${X_MOON_CACHE_MIN_IDLE_CONNS:0}
  max_idle_conns: ${X_MOON_CACHE_MAX_IDLE_CONNS:0}
  max_active_conns: ${X_MOON_CACHE_MAX_ACTIVE_CONNS:0}
  conn_max_idle_time: ${X_MOON_CACHE_CONN_MAX_IDLE_TIME:0s}
  conn_max_lifetime: ${X_MOON_CACHE_CONN_MAX_LIFETIME:0s}
  disable_identity: ${X_MOON_CACHE_DISABLE_IDENTITY:false}
  identity_suffix: ${X_MOON_CACHE_IDENTITY_SUFFIX}
  unstable_resp3: ${X_MOON_CACHE_UNSTABLE_RESP3:false}