data:
  main:
    driver: ${X_MOON_DATA_MAIN_DRIVER:SQLITE}
    dsn: ${X_MOON_DATA_MAIN_DSN:file:main.db?cache=shared&mode=rwc}
    debug: ${X_MOON_DATA_MAIN_DEBUG:true}
    use_system_log: ${X_MOON_DATA_MAIN_USE_SYSTEM_LOG:false}
  biz:
    driver: ${X_MOON_DATA_BIZ_DRIVER:SQLITE}
    dsn: ${X_MOON_DATA_BIZ_DSN:file:biz.db?cache=shared&mode=rwc}
    debug: ${X_MOON_DATA_BIZ_DEBUG:true}
    use_system_log: ${X_MOON_DATA_BIZ_USE_SYSTEM_LOG:false}
  alarm:
    driver: ${X_MOON_DATA_ALARM_DRIVER:SQLITE}
    dsn: ${X_MOON_DATA_ALARM_DSN:file:alarm.db?cache=shared&mode=rwc}
    debug: ${X_MOON_DATA_ALARM_DEBUG:true}
    use_system_log: ${X_MOON_DATA_ALARM_USE_SYSTEM_LOG:false}

cache:
  driver: ${X_MOON_CACHE_DRIVER:MEMORY}
  network: ${X_MOON_CACHE_NETWORK:tcp}
  addr: ${X_MOON_CACHE_ADDR:127.0.0.1:6379}
  password: ${X_MOON_CACHE_PASSWORD:}
  db: ${X_MOON_CACHE_DB:0}
  read_timeout: ${X_MOON_CACHE_READ_TIMEOUT:5s}
  write_timeout: ${X_MOON_CACHE_WRITE_TIMEOUT:5s}
  dial_timeout: ${X_MOON_CACHE_DIAL_TIMEOUT:5s}
  client_name: ${X_MOON_CACHE_CLIENT_NAME:}
  protocol: ${X_MOON_CACHE_PROTOCOL:0}
  username: ${X_MOON_CACHE_USERNAME:}
  max_retries: ${X_MOON_CACHE_MAX_RETRIES:0}
  min_retry_backoff: ${X_MOON_CACHE_MIN_RETRY_BACKOFF:0s}
  max_retry_backoff: ${X_MOON_CACHE_MAX_RETRY_BACKOFF:0s}
  context_timeout_enabled: ${X_MOON_CACHE_CONTEXT_TIMEOUT_ENABLED:false}
  pool_fifo: ${X_MOON_CACHE_POOL_FIFO:false}
  pool_size: ${X_MOON_CACHE_POOL_SIZE:0}
  pool_timeout: ${X_MOON_CACHE_POOL_TIMEOUT:0s}
  min_idle_conns: ${X_MOON_CACHE_MIN_IDLE_CONNS:0}
  max_idle_conns: ${X_MOON_CACHE_MAX_IDLE_CONNS:0}
  max_active_conns: ${X_MOON_CACHE_MAX_ACTIVE_CONNS:0}
  conn_max_idle_time: ${X_MOON_CACHE_CONN_MAX_IDLE_TIME:0s}
  conn_max_lifetime: ${X_MOON_CACHE_CONN_MAX_LIFETIME:0s}
  disable_identity: ${X_MOON_CACHE_DISABLE_IDENTITY:false}
  identity_suffix: ${X_MOON_CACHE_IDENTITY_SUFFIX:}
  unstable_resp3: ${X_MOON_CACHE_UNSTABLE_RESP3:false}