auth:
  jwt:
    sign_key: ${X_MOON_RABBIT_AUTH_JWT_SIGN_KEY:secret}
    issuer: ${X_MOON_RABBIT_AUTH_JWT_ISSUER:moon-rabbit}
    expire: ${X_MOON_RABBIT_AUTH_JWT_EXPIRE:3600s}
    allow_operations:
      - /api.common.Health/Check
