hooks:
  - name: dingtalk
    app: DINGTALK
    url: https://oapi.dingtalk.com/robot/send?access_token=xxx
    secret: xxx
    token: xxx

  - name: wechat
    app: WECHAT
    url: https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=xxx

  - name: feishu
    app: FEISHU
    url: https://open.feishu.cn/open-apis/bot/v2/hook/xxx
    secret: xxx
    token: xxx

  - name: other
    app: OTHER
    url: http://xxx.com/api/push
    username: xxx
    password: xxx
    token: xxx
    secret: xxx
