recipient:
  email: [ ]
  sms: [ ]
  voice: [ ]
  hook: [ ]

receivers:
  team_1_1:
    email: [ ]
    sms: [ ]
    voice: [ ]
    hook: [ ]

templates:
  email:
    xxx_template:
  sms:
    xxx_template:
  hook:
    dingtalk:
      xxx_template:
    feishu:
      xxx_template:
    wechat:
      xxx_template:
    other:
      xxx_template: