environment: ${X_MOON_RABBIT_ENVIRONMENT:DEV}

server:
  name: ${X_MOON_RABBIT_SERVER_NAME:rabbit}
  metadata:
    secret: ${X_MOON_RABBIT_SERVER_SECRET:}
  http:
    network: ${X_MOON_RABBIT_HTTP_NETWORK:tcp}
    addr: ${X_MOON_RABBIT_HTTP_ADDR:0.0.0.0:8080}
    timeout: ${X_MOON_RABBIT_HTTP_TIMEOUT:5s}
    allow_operations:
      - /api.rabbit.common.Health/Check
    allow_headers: ${X_MOON_RABBIT_HTTP_ALLOW_HEADERS:['*']}
    allow_methods: ${X_MOON_RABBIT_HTTP_ALLOW_METHODS:['*']}
    allow_origins: ${X_MOON_RABBIT_HTTP_ALLOW_ORIGINS:['*']}

  grpc:
    network: ${X_MOON_RABBIT_GRPC_NETWORK:tcp}
    addr: ${X_MOON_RABBIT_GRPC_ADDR:0.0.0.0:9090}
    timeout: ${X_MOON_RABBIT_GRPC_TIMEOUT:5s}

registry:
  driver: ${X_MOON_RABBIT_REGISTRY_DRIVER:ETCD}
  enable: ${X_MOON_RABBIT_REGISTRY_ENABLE:false}
  etcd:
    endpoints: ${X_MOON_RABBIT_REGISTRY_ETCD_ENDPOINTS:['127.0.0.1:2379']}
    timeout: ${X_MOON_RABBIT_REGISTRY_ETCD_TIMEOUT:5s}
    username: ${X_MOON_RABBIT_REGISTRY_ETCD_USERNAME:}
    password: ${X_MOON_RABBIT_REGISTRY_ETCD_PASSWORD:}

micro_server:
  endpoint: ${X_MOON_RABBIT_MICRO_SERVER_ENDPOINT:127.0.0.1:9090}
  secret: ${X_MOON_RABBIT_MICRO_SERVER_SECRET:}
  timeout: ${X_MOON_RABBIT_MICRO_SERVER_TIMEOUT:5s}
  network: ${X_MOON_RABBIT_MICRO_SERVER_NETWORK:GRPC}
  version: ${X_MOON_RABBIT_MICRO_SERVER_VERSION:1.0.0}
  name: ${X_MOON_RABBIT_MICRO_SERVER_NAME:rabbit}

team_ids: ${X_MOON_RABBIT_TEAM_IDS:[]}

online_interval: ${X_MOON_RABBIT_ONLINE_INTERVAL:60s}
