templates:
  emails:
    default:
      name: default
      parameters: ${X_MOON_RABBIT_EMAIL_PARAMETERS:}
      subject: ${X_MOON_RABBIT_EMAIL_SUBJECT:}
      content_type: ${X_MOON_RABBIT_EMAIL_CONTENT_TYPE:}
      attachment: ${X_MOON_RABBIT_EMAIL_ATTACHMENT:}
      cc: ${X_MOON_RABBIT_EMAIL_CC:}
  smss:
    default:
      name: default
      parameters: ${X_MOON_RABBIT_SMS_PARAMETERS:}
      template_code: ${X_MOON_RABBIT_SMS_TEMPLATE_CODE:}
  hooks:
    default:
      dingtalk: ${X_MOON_RABBIT_HOOK_DINGTALK:}
      wechat: ${X_MOON_RABBIT_HOOK_WECHAT:}
      feishu: ${X_MOON_RABBIT_HOOK_FEISHU:}
      other: ${X_MOON_RABBIT_HOOK_OTHER:}
